<a href="https://colab.research.google.com/github/Mereyabutalipova/week3_lab/blob/main/exercises_week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [1]:
import torch

# TODO: Create a scalar tensor
scalar =  torch.tensor(42)

# Print details
print(f"Scalar value: {scalar}")
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

Scalar value: 42
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [2]:
# TODO: Create a vector tensor
vector = torch.tensor([1, 2, 3, 4])

# Print details
print(f"Vector: {vector}")
print(f"Number of dimensions (ndim): {vector.ndim}")
print(f"Shape: {vector.shape}")

Vector: tensor([1, 2, 3, 4])
Number of dimensions (ndim): 1
Shape: torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [3]:
# TODO: Create a matrix tensor
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

# Print details
print(f"Matrix:\n{matrix}")
print(f"Number of dimensions (ndim): {matrix.ndim}")
print(f"Shape: {matrix.shape}")

Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions (ndim): 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [4]:
# TODO: Create a 3D tensor
tensor_3d = torch.arange(1, 9).reshape(2, 2, 2)

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Number of dimensions: 3
Shape: torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [5]:
# TODO: Create random tensor
random_tensor = torch.rand(4, 4)

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.1980, 0.8756, 0.5283, 0.0758],
        [0.2116, 0.8853, 0.9160, 0.2832],
        [0.6809, 0.2681, 0.4712, 0.6831],
        [0.9823, 0.3816, 0.1440, 0.6505]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [6]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(size=(3, 224, 224))

print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([3, 224, 224])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [7]:
# TODO: Create zeros tensor
zeros = torch.zeros(5, 5)

print(zeros)
print(f"Shape: {zeros.shape}")

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Shape: torch.Size([5, 5])


### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [8]:
import torch

random_tensor = torch.rand(3, 3)

# TODO: Create ones like
ones_like = torch.ones_like(input=random_tensor)

print(f"Original random tensor:\n{random_tensor}")
print(f"\nOnes like tensor:\n{ones_like}")
print(f"\nShape check: {ones_like.shape}")

Original random tensor:
tensor([[0.7145, 0.1310, 0.8233],
        [0.9530, 0.3090, 0.0943],
        [0.7129, 0.5975, 0.2334]])

Ones like tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Shape check: torch.Size([3, 3])


## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [9]:
# TODO: Create range tensor
range_tensor = torch.arange(start=0, end=21, step=2)

print(range_tensor)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])


## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [10]:
# TODO: float16 tensor
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

# TODO: int64 tensor
int64_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.int64)

print(f"Float16 Tensor: {float16_tensor}, Dtype: {float16_tensor.dtype}")
print(f"Int64 Tensor: {int64_tensor}, Dtype: {int64_tensor.dtype}")

Float16 Tensor: tensor([1., 2., 3.], dtype=torch.float16), Dtype: torch.float16
Int64 Tensor: tensor([1, 2, 3]), Dtype: torch.int64


### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [11]:
# TODO: Change dtype
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
float32_tensor = float16_tensor.to(torch.float32)

print(f"Tensor: {float32_tensor}")
print(f"New Dtype: {float32_tensor.dtype}")


Tensor: tensor([1., 2., 3.])
New Dtype: torch.float32


## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [12]:
# TODO: Create tensor and print info
info_tensor = torch.rand(2, 3, 4)

print(f"Shape: {info_tensor.shape}")
print(f"Datatype: {info_tensor.dtype}")
print(f"Device: {info_tensor.device}")

Shape: torch.Size([2, 3, 4])
Datatype: torch.float32
Device: cpu


## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [16]:
tensor = torch.tensor([10, 20, 30])
# TODO: Add 5
tensor_add = tensor + 5

# TODO: Subtract 10
tensor_sub = tensor - 10

# TODO: Multiply by 2
tensor_mul = tensor * 2

# TODO: Divide by 10
tensor_div = tensor / 10

print(f"Original: {tensor}")
print(f"Addition (+5): {tensor_add}")
print(f"Subtraction (-10): {tensor_sub}")
print(f"Multiplication (*2): {tensor_mul}")
print(f"Division (/10): {tensor_div}")

Original: tensor([10, 20, 30])
Addition (+5): tensor([15, 25, 35])
Subtraction (-10): tensor([ 0, 10, 20])
Multiplication (*2): tensor([20, 40, 60])
Division (/10): tensor([1., 2., 3.])


### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [18]:
# TODO: Create A and B
A = torch.rand(2, 3)
B = torch.rand(3, 2)

# TODO: Matrix mul using torch.mm
result_mm = torch.mm(A, B)

# TODO: Matrix mul using @
result_at = A @ B

print(f"Matrix A:\n{A}")
print(f"Matrix B:\n{B}")
print(f"\nResult (using torch.mm):\n{result_mm}")
print(f"Result (using @):\n{result_at}")
print(f"\nResult Shape: {result_at.shape}")

Matrix A:
tensor([[0.6098, 0.0956, 0.8725],
        [0.0437, 0.4988, 0.4903]])
Matrix B:
tensor([[0.1976, 0.0888],
        [0.6954, 0.8295],
        [0.8246, 0.2804]])

Result (using torch.mm):
tensor([[0.9064, 0.3781],
        [0.7597, 0.5551]])
Result (using @):
tensor([[0.9064, 0.3781],
        [0.7597, 0.5551]])

Result Shape: torch.Size([2, 2])


## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [19]:
agg_tensor = torch.arange(0, 101)
# TODO: Min
tensor_min = agg_tensor.min()

# TODO: Max
tensor_max = agg_tensor.max()

# TODO: Mean (note: may need to cast to float)
tensor_mean = agg_tensor.type(torch.float32).mean()

# TODO: Sum
tensor_sum = agg_tensor.sum()

print(f"Minimum: {tensor_min}")
print(f"Maximum: {tensor_max}")
print(f"Mean: {tensor_mean}")
print(f"Sum: {tensor_sum}")

Minimum: 0
Maximum: 100
Mean: 50.0
Sum: 5050


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [20]:
agg_tensor = torch.arange(0, 101)

# TODO: Argmin
min_index = agg_tensor.argmin()

# TODO: Argmax
max_index = agg_tensor.argmax()

print(f"Index of minimum: {min_index}")
print(f"Index of maximum: {max_index}")

Index of minimum: 0
Index of maximum: 100


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [21]:
reshape_tensor = torch.arange(10)
# TODO: Reshape
reshaped = reshape_tensor.reshape(2, 5)

print(f"Original shape: {reshape_tensor.shape}")
print(f"Reshaped tensor:\n{reshaped}")
print(f"New shape: {reshaped.shape}")

Original shape: torch.Size([10])
Reshaped tensor:
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
New shape: torch.Size([2, 5])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [22]:
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)
# TODO: Stack vertically (dim=0)
stacked_v = torch.stack([tensor1, tensor2], dim=0)

# TODO: Stack horizontally (dim=1)
stacked_h = torch.stack([tensor1, tensor2], dim=1)

print(f"Tensor 1:\n{tensor1}")
print(f"Tensor 2:\n{tensor2}")
print(f"\nStacked Vertically (dim=0) shape: {stacked_v.shape}")
print(f"Stacked Horizontally (dim=1) shape: {stacked_h.shape}")

Tensor 1:
tensor([[0.1938, 0.1623],
        [0.3037, 0.6228]])
Tensor 2:
tensor([[0.4261, 0.5564],
        [0.5371, 0.7538]])

Stacked Vertically (dim=0) shape: torch.Size([2, 2, 2])
Stacked Horizontally (dim=1) shape: torch.Size([2, 2, 2])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [23]:
squeeze_tensor = torch.rand(1, 3, 1)
# TODO: Squeeze
squeezed = tensor.squeeze()

# TODO: Unsqueeze on dim=0
unsqueezed = squeezed.unsqueeze(dim=0)

print(f"Original shape: {tensor.shape}")
print(f"Squeezed shape: {squeezed.shape}")
print(f"Unsqueezed (dim=0) shape: {unsqueezed.shape}")

Original shape: torch.Size([3])
Squeezed shape: torch.Size([3])
Unsqueezed (dim=0) shape: torch.Size([1, 3])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [24]:
image_tensor = torch.rand(3, 100, 100)
# TODO: Permute
permuted = image_tensor.permute(1, 2, 0)

print(f"Original shape: {image_tensor.shape}")
print(f"Permuted shape: {permuted.shape}")

Original shape: torch.Size([3, 100, 100])
Permuted shape: torch.Size([100, 100, 3])


## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [25]:
index_tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
# TODO: Get 5
value_5 = index_tensor[0, 1, 1]

# TODO: Get second row [4,5,6]
second_row = index_tensor[0, 1, :]

print(f"Entire tensor:\n{index_tensor}")
print(f"Shape: {index_tensor.shape}")
print(f"\nValue 5: {value_5}")
print(f"Second row: {second_row}")

Entire tensor:
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Shape: torch.Size([1, 3, 3])

Value 5: 5
Second row: tensor([4, 5, 6])


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [26]:
import numpy as np
numpy_array = np.array([1,2,3,4])
# TODO: Convert to tensor
from_numpy = torch.from_numpy(numpy_array)

print(f"NumPy array: {numpy_array}")
print(f"PyTorch tensor: {from_numpy}")

NumPy array: [1 2 3 4]
PyTorch tensor: tensor([1, 2, 3, 4])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [27]:
pytorch_tensor = torch.tensor([5,6,7,8])
# TODO: Convert to NumPy
to_numpy =  pytorch_tensor.numpy()

print(f"PyTorch tensor: {pytorch_tensor}")
print(f"Converted NumPy array: {to_numpy}")
print(f"Type: {type(to_numpy)}")

PyTorch tensor: tensor([5, 6, 7, 8])
Converted NumPy array: [5 6 7 8]
Type: <class 'numpy.ndarray'>


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [28]:
# TODO: Set seed
torch.manual_seed(77)
rand1 = torch.rand(2,2)

# TODO: Reset seed for second tensor
torch.manual_seed(77)
rand2 = torch.rand(2, 2)

# Check equality
print(f"Tensor 1:\n{rand1}")
print(f"\nTensor 2:\n{rand2}")
print(f"\nAre they equal?\n{rand1 == rand2}")

Tensor 1:
tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])

Tensor 2:
tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])

Are they equal?
tensor([[True, True],
        [True, True]])


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [29]:
# TODO: Set device
device = "cuda" if torch.cuda.is_available() else "cpu"

print(f"Using device: {device}")

test_tensor = torch.tensor([1, 2, 3], device=device)
print(f"Tensor is on: {test_tensor.device}")

Using device: cpu
Tensor is on: cpu


### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [30]:
gpu_tensor = torch.tensor([10, 20, 30])
# TODO: Move to device
gpu_tensor = gpu_tensor.to(device)

# TODO: Move back to CPU and to NumPy
cpu_numpy = gpu_tensor.cpu().numpy()

print(f"Device: {gpu_tensor.device}")
print(f"NumPy Result: {numpy_array}")
print(f"Result Type: {type(cpu_numpy)}")

Device: cpu
NumPy Result: [1 2 3 4]
Result Type: <class 'numpy.ndarray'>
